// Tipos para o sistema de jovens
export const JOVEM_TYPES = {
  // Estrutura básica de um jovem
  JOVEM: {
    id: 'string',
    nome_completo: 'string',
    whatsapp: 'string',
    data_nasc: 'string',
    idade: 'number',
    sexo: 'string',
    estado_civil: 'string',
    namora: 'boolean',
    tem_filho: 'boolean',
    trabalha: 'boolean',
    local_trabalho: 'string',
    escolaridade: 'string',
    formacao: 'string',
    tem_dividas: 'boolean',
    valor_divida: 'number',
    tempo_igreja: 'string',
    batizado_aguas: 'boolean',
    data_batismo_aguas: 'string',
    batizado_es: 'boolean',
    data_batismo_es: 'string',
    condicao: 'string',
    tempo_condicao: 'string',
    responsabilidade_igreja: 'string',
    ja_obra_altar: 'boolean',
    ja_obreiro: 'boolean',
    ja_colaborador: 'boolean',
    afastado: 'boolean',
    data_afastamento: 'string',
    motivo_afastamento: 'string',
    data_retorno: 'string',
    pais_na_igreja: 'boolean',
    familiares_igreja: 'boolean',
    deseja_altar: 'boolean',
    formado_intellimen: 'boolean',
    fazendo_desafios: 'boolean',
    qual_desafio: 'string',
    edicao: 'string',
    instagram: 'string',
    facebook: 'string',
    tiktok: 'string',
    obs_redes: 'string',
    observacao: 'string',
    testemunho: 'string',
    aprovado: 'string',
    data_cadastro: 'string',
    estado_id: 'string',
    bloco_id: 'string',
    regiao_id: 'string',
    igreja_id: 'string',
    edicao_id: 'string',
    usuario_id: 'string',
    tem_avaliacoes: 'boolean',
    // Dados relacionados
    estado: 'object',
    bloco: 'object',
    regiao: 'object',
    igreja: 'object',
    edicao_obj: 'object'
  }
};
